### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by dickdoof** [ZUGFeRD/mustangserver#1]
Could not find artifact org.jfrog.jade.plugins.common:jade-plugin-common:pom:1.3.8 in mustang-mvn-repo (https://raw.github.com/ZUGFeRD/mustangproject/mvn-repo/)

**Comment by jstaerk** [comment]
now it should work again, but please note that the project is outdated, since there had been no contributions at all for so long we  rewrote it (with mustang 2.3, *this* version is still 1.7.somethingish) in spring boot and made it proprietary. I can send you a test version if you email me at jochen at zugferd.org.
